//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demos.WebformsMVP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int UserProfileId { get; set; }
        public int ActivityTypeId { get; set; }
        public string OtherActivity { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public int Duration { get; set; }
        public int Score { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
    
        public virtual ActivityType ActivityType { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
