name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore Nuget Packages
      run: nuget restore Demos.WebformsMVP.sln
      
    - name: Build
      run: |
        msbuild.exe Demos.WebformsMVP.sln /nologo /nr:false /p:DeployOnBuild=false /p:platform="Any CPU" /p:configuration="Release"

    - name: Test
      run: dotnet test --no-restore --verbosity normal
